- name: Configure and Start Nginx
  become: yes
  tasks:
    - name: Ensure the system is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx configuration is valid
      command: nginx -t
      register: nginx_test
      failed_when: nginx_test.rc != 0
      ignore_errors: yes

    - name: Display Nginx configuration test result (if it failed)
      debug:
        msg: "{{ nginx_test.stderr }}"
      when: nginx_test.rc != 0

    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
      when: nginx_test.rc == 0

    - name: index
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

